theme: jekyll-theme-minimal
title: Apresentação sobre Combustão
description: Apresentação interativa sobre combustão com animações e gráficos dinâmicos
baseurl: "/apresentacao-combustao"
url: "https://nexymf.github.io"
